# Generated by Django 6.0 on 2026-04-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_category_options_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon_type',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
