# Generated by Django 6.0 on 2026-04-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_skill_icon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='icon_type',
            field=models.CharField(blank=True, choices=[('devicon', 'Devicon'), ('fa', 'FontAwesome')], max_length=150),
        ),
    ]
