# Generated by Django 6.0 on 2026-04-13 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_interest_alter_skill_options_category_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interest',
            options={'ordering': ['name']},
        ),
    ]
