# Generated by Django 6.0 on 2026-04-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_interest_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='icon_class',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
