# Generated by Django 6.0 on 2026-08-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_contactform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='gpa',
            field=models.CharField(max_length=10),
        ),
    ]
